# This workflow builds and tests a Go project
# For more information, see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Install Dependencies
      run: go mod tidy

    - name: Build
      run: go build -v ./...

    - name: Run Tests
      run: go test ./...

    - name: Lint Code
      run: |
        go install golang.org/x/lint/golint@latest
        golint ./...

    - name: Verify Go Version
      run: go version
